<?php

namespace Plugin\ChatworkApi\Repository;

use Doctrine\Persistence\ManagerRegistry;
use Eccube\Repository\AbstractRepository;
use Plugin\ChatworkApi\Entity\Config;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Config::class);
    }

    /**
     * @param int $id
     *
     * @return Config
     *
     * @throws \Exception
     */
    public function get($id = 1)
    {
        $Config = $this->find($id);

        if (null === $Config) {
            $Config = new \Plugin\ChatworkApi\Entity\Config();
            $this->_em->persist($Config); // ← 新規作成
            $this->_em->flush();
        }

        return $Config;
    }
}
